spring.application.name=sql-relations
spring.datasource.url=jdbc:postgresql://localhost:5432/18D3
spring.datasource.username=p****
spring.datasource.password=7*****
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

